### ISSUE TITLE
Location of Latest Release of YouTrack Hardcoded

### ISSUE THREAD

**Issue by marshallwp** [oukooveu/ansible-role-youtrack#5]
Currently the location of the latest release of YouTrack (where the symbolic link is created) is hardcoded to `{{ youtrack_home_dir }}/youtrack` in various locations such as:

- The symbolic link creation step https://github.com/oukooveu/ansible-role-youtrack/blob/83057e8b37eb272afa5ab272ac366eb5bc0a8882/tasks/main.yml#L18-L27
- The installed version check https://github.com/oukooveu/ansible-role-youtrack/blob/83057e8b37eb272afa5ab272ac366eb5bc0a8882/tasks/configure.yml#L2-L5
- The YouTrack service template https://github.com/oukooveu/ansible-role-youtrack/blob/83057e8b37eb272afa5ab272ac366eb5bc0a8882/templates/youtrack.service.j2#L20-L21

This makes it extremely problematic if you want to install YouTrack to, say, `/opt/youtrack`.  Especially when SELinux gets involved.  I propose creating a new variable to specify the destination of the symbolic link, allowing for some needed configuration.  Naming is a bit up in the air as `youtrack_home_dir` is already taken (and this location will serve as what YouTrack documentation calls the "Home Directory"), but in the related pull I'll be creating shortly, I'm calling it `youtrack_base_dir`.

**Comment by oukooveu** [comment]
> This makes it extremely problematic if you want to install YouTrack to, say, /opt/youtrack. 

Could you please explain a little bit when this approach is not suitable or breaks something? Don't understand how the custom link name can help.

**Comment by marshallwp** [comment]
Alright, let's say we want to install things to `/opt/youtrack`.  We could take several approaches to that:

| Approach | Problem |
| ---------- | -------- |
| Set `youtrack_home_dir` to `/opt/youtrack` so the link will be at `/opt/youtrack/youtrack`. | This transforms the entire `/opt/youtrack` directory into a user's home directory.  SELinux lables will be all over the place and it will be polluted with user home-specific files. |
| Leave `youtrack_home_dir` alone, but move the other dirs into subdirectories of `/opt/youtrack` | Files are nicely segregated and organized, but YouTrack cannot start. SELinux doesn't like it when a user attempts to start non-user programs from within their home. I'm not entirely certain why, but the cause appears to be SELinux labeling that considers files in `/opt` to be system files and files in `/home` to be user files. Changing those labels could work, but it would also make them incorrect. |

By breaking the link destination into its own variable you can avoid both of by placing the link in `/opt/youtrack` as well.  It also lets users have a custom name for the link.

For example, my directory layout using the branch from the pull request is:
```yaml
youtrack_home_dir: "/home/{{ youtrack_user }}"
youtrack_release_link: "/opt/youtrack/latest"
youtrack_data_dir: "/opt/youtrack/data"
youtrack_logs_dir: "/opt/youtrack/log"
youtrack_releases_dir: "/opt/youtrack/releases"
youtrack_backups_dir: "/opt/youtrack/backups"
```
